"""empty message

Revision ID: 0246d3b14df4
Revises: 
Create Date: 2025-05-09 23:47:43.621608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0246d3b14df4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('url_image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('gender', sa.String(length=30), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('avatar', sa.String(length=200), nullable=True),
    sa.Column('telegram_contact', sa.String(length=50), nullable=True),
    sa.Column('discord_contact', sa.String(length=50), nullable=True),
    sa.Column('steam_contact', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('details', sa.String(length=500), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lobbies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('skill_level', sa.Integer(), nullable=True),
    sa.Column('goal', sa.String(length=100), nullable=True),
    sa.Column('slots', sa.Integer(), nullable=True),
    sa.Column('filled_slots', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lobby_users_association',
    sa.Column('lobby_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lobby_users_association')
    op.drop_table('lobbies')
    op.drop_table('bids')
    op.drop_table('users')
    op.drop_table('games')
    # ### end Alembic commands ###
