"""empty message

Revision ID: 29327e7afafa
Revises: 4b3dbcaef3d0
Create Date: 2025-05-09 22:47:24.515491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29327e7afafa'
down_revision = '4b3dbcaef3d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lobbies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('filled_slots', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])
        batch_op.drop_column('filled_clots')

    with op.batch_alter_table('lobby_users_association', schema=None) as batch_op:
        batch_op.drop_constraint('lobby_users_association_lobby_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('lobby_users_association_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'lobbies', ['lobby_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lobby_users_association', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('lobby_users_association_user_id_fkey', 'lobbies', ['user_id'], ['id'])
        batch_op.create_foreign_key('lobby_users_association_lobby_id_fkey', 'users', ['lobby_id'], ['id'])

    with op.batch_alter_table('lobbies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filled_clots', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('filled_slots')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
