"""empty message

Revision ID: 4b3dbcaef3d0
Revises: e00909048174
Create Date: 2025-05-09 22:13:15.853238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b3dbcaef3d0'
down_revision = 'e00909048174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lobbies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=True),
    sa.Column('skill_level', sa.Integer(), nullable=True),
    sa.Column('goal', sa.String(length=100), nullable=True),
    sa.Column('slots', sa.Integer(), nullable=True),
    sa.Column('filled_clots', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lobby_users_association',
    sa.Column('lobby_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lobby_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['lobbies.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lobby_users_association')
    op.drop_table('lobbies')
    # ### end Alembic commands ###
