"""empty message

Revision ID: e00909048174
Revises: 9bfa7995ab85
Create Date: 2025-05-09 00:16:46.468008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e00909048174'
down_revision = '9bfa7995ab85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('avatar', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('telegram_contact', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('discord_contact', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('steam_contact', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('steam_contact')
        batch_op.drop_column('discord_contact')
        batch_op.drop_column('telegram_contact')
        batch_op.drop_column('avatar')
        batch_op.drop_column('bio')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
